version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mywebapp
    ports:
      - "8888:8080" # Maps port 8888 on the host to port 8080 in the container
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: mywebapp-db
    ports:
      - "5432:5432" # Maps PostgreSQL port
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro # Automatically initializes the database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
